apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blueapp
  name: blueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueapp
  template:
    metadata:
      labels:
        app: blueapp
    spec:
      containers:
      - image: node:current-alpine3.19
        name: node
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: blueapp-service
spec:
  selector:
    app: blueapp
  ports:
  - name: webserver
    protocol: TCP
    port: 8080
    targetPort: http
