apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blueapp
  name: blueapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueapp
  template:
    metadata:
      labels:
        app: blueapp
    spec:
      containers:
      - image: istio/examples-helloworld-v1
        name: node
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: blueapp-service
spec:
  selector:
    app: blueapp
  ports:
  - name: webserver
    protocol: TCP
    port: 8080
    targetPort: http
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: buleapp
  labels:
    app.kubernetes.io/instance: gitops-ocp-sample
spec:
  to:
    kind: Service
    name: blueapp-service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    destinationCACertificate: ''
  port:
    targetPort: webserver
