apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greenapp
  name: greenapp
  namespace: technical-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenapp
  template:
    metadata:
      labels:
        app: greenapp
    spec:
      containers:
      - image: ocnexus-ref01.fortisbank.com.pl:18079/nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: blueapp-service
  namespace: technical-beta
spec:
  selector:
    app: greenapp
  ports:
  - name: webserver
    protocol: TCP
    port: 80
    targetPort: http
