apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blueapp
  name: blueapp
  namespace: technical-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueapp
  template:
    metadata:
      labels:
        app: blueapp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: blueapp-service
  namespace: technical-beta
spec:
  selector:
    app: blueapp
  ports:
  - name: webserver
    protocol: TCP
    port: 80
    targetPort: http
